apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: gachu/front-react:v1.0
          ports:
            - containerPort: 4100
          env:
            - name: API
              valueFrom:
                configMapKeyRef:
                  name: config-front
                  key: API
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-front
                  key: PORT