apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
spec:
  selector:
    matchLabels:
      app: front-deploy
  template:
    metadata:
      labels:
        app: front-deploy
    spec:
      containers:
        - name: front-deploy
          image: DOCKER_IMAGE:TAG
          ports:
            - containerPort: 4100
          env:
            - name: API
              valueFrom:
                configMapKeyRef:
                  name: config-front
                  key: API
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-front
                  key: PORT