apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
  labels:
    app: back-deploy
spec:
  selector:
    matchLabels:
      app: back-deploy
  template:
    metadata:
      labels:
        app: back-deploy
    spec:
      containers:
        - name: back-deploy
          image: DOCKER_IMAGE:TAG
          ports:
          - containerPort: 8000
          env:
            - name: DB_DATABASE
              valueFrom:
                  configMapKeyRef:
                      name: db-config
                      key: db_name
            - name: DB_HOST
              value: db
            - name: DB_PORT
              valueFrom:
                  configMapKeyRef:
                      name: db-config
                      key: db_port
            - name: DB_USERNAME
              valueFrom:
                  secretKeyRef:
                      name: db-secret
                      key: db_user
            - name: DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: db-secret
                      key: db_pass
            - name: DB_CONNECTION
              value: pgsql