apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: gachu/back-eam:1.0
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_pass
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db_name
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db_port