apiVersion: v1
kind: Service
metadata: 
  name: back-deploy
  labels:
    app: back-deploy
spec:
  type: NodePort
  selector: 
    app: back-deploy
  ports:
   - protocol: TCP
     nodePort: 30301
     port: 8000